# based on the template from
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

# image: openjdk:17
## we use a proxied docker image in order to not run into a pull rate limit
image: harbor.uni-muenster.de/proxy-docker/library/openjdk:17

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update
  - apt-get -y install ant
  - apt-get -y install unzip

# For merge requests do not `deploy` but only run `verify`.
.verify: &verify
  stage: test
  tags:
    - privileged
  script:
    - './mvnw verify -s ci_settings.xml'
    - 'target/bin/test.sh'
  except:
    - master

# Verify merge requests
verify:jdk11:
  <<: *verify

# deploy using ci_settings.xml as maven settings
# see https://gitlab.com/help/user/packages/maven_repository/index.md#creating-maven-packages-with-gitlab-cicd-using-maven
deploy:jdk11:
  tags:
    - privileged
  script:
    - './mvnw verify -s ci_settings.xml'
    - 'target/bin/test.sh'
  artifacts:
    paths:
      - target
  only:
    - master
    - tags

pages:
  stage: deploy
  script:
    - mkdir -p public
    - ls -la
    - unzip target/*-package.zip -d public
    - cp -v target/*-package.zip public/
    - cp -v target/descriptor.xml public/
    - cp -v target/*-oxygen-distribution.jar public/
    - cp -v target/seed-config.yaml public/
  artifacts:
    paths:
      - public
  only:
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
